### ISSUE TITLE
Make one option

### ISSUE THREAD

**Issue by Paradox75831004** [KodiCraft/TermSpeak#2]
Add to the config - so that only when the walkie-talkie is in your hand and you enter the terminal, then it turns on automatically. If the radio is turned on, but not in your hands, it will not be active when you enter the terminal.

**Comment by rto700** [comment]
Another sugestion. Is that possible to add a option to enable the walkie-talkie by holding LMB, when there is powered one in the inventory? Which is more vanila like, and can be used with the walkie-talkie slot mod, cause it is not possible to hold walkie-talkie and to use the terminal simultaneously with that mod.

**Comment by KodiCraft** [comment]
> Another sugestion. Is that possible to add a option to enable the walkie-talkie by holding LMB, when there is powered one in the inventory? Which is more vanila like, and can be used with the walkie-talkie slot mod, cause it is not possible to hold walkie-talkie and to use the terminal simultaneously with that mod.

I'll make another issue for that. Closing this one as implemented.
